### PR TITLE
Update to 0.47.0

### PR DESCRIPTION
**Pull request by mattelacchiato**

### CODE REVIEW

**Comment by DZvO** [comment]
@nbadal 🏓 🙏

Thanks for this awesome plugin btw, and thanks to @mattelacchiato for creating this PR

**Comment by mrmans0n** [comment]
Should this be targeting 0.47.1? It's the latest one, launched 2 weeks ago

**Comment by mattelacchiato** [comment]
Well, this PR is now open for 27 days. If we wait longer for merging this, the next version of ktlint will be released in the meantime.

What is currently blocking this PR to be merged?

**Comment by nbadal** [comment]
Hey all! Sorry for the delay, my day job has been consuming more of my overall dev time recently. In addition, the only projects in which I can utilize my own plugin rely on the (seemingly dormant, currently broken) https://github.com/JLLeitschuh/ktlint-gradle/ plugin 😦 

I've automated Pull Requests for IDE versions, but I should probably do the same for ktlint versions as well! Reviewing this now...

**Comment by nbadal** [comment]
There is a significant API change in 0.47.x that I'm still working through - lots of deprecations etc. I don't want to release this upgrade without ensuring that the new API meets the needs of this plugin.

**Comment by mattelacchiato** [comment]
Thanks for your feedback! This helps a lot and i can fully understand your situation.
Thank you for your work 👍

**Comment by nbadal** [comment]
0.48 was merged separately, closing.

**Pull request closed without merging**
